### ISSUE TITLE
teraflops doesn't seem to like its own tfstate when using opentofu

### ISSUE THREAD

**Issue by KiaraGrouwstra** [aanderse/teraflops#16]
when using `opentofu` with teraflops, once a successful run has generated a `terraform.tfstate` file, subsequent runs seem to get me the error:

> opentofu does not support state version 4, please update

(tried opentofu versions from nixpkgs 24.05 and unstable.)

using `terraform` instead, this issue seems not to occur.

**Comment by aanderse** [comment]
is this a known issue in nixpkgs at all, or something specific to `teraflops`?

**Comment by KiaraGrouwstra** [comment]
i've had trouble finding reports within the nix community.
it looks like i'm getting similar issues using terraform tho after all, so it may be on me to find a minimum repro.

c.f. #15 which also seemed about TF state
